Vagrant.configure("2") do |config|

    config.vm.define "ftp_server" do |ftp|
      ftp.vm.box = "ubuntu/bionic64"
      ftp.vm.network "public_network", bridge: "eno2"
      ftp.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y vsftpd
        sudo cp /etc/vsftpd.conf /etc/vsftpd.conf.orig
  
        echo "anonymous_enable=YES" | sudo tee -a /etc/vsftpd.conf
        echo "local_enable=YES" | sudo tee -a /etc/vsftpd.conf
        echo "write_enable=YES" | sudo tee -a /etc/vsftpd.conf
        echo "local_umask=022" | sudo tee -a /etc/vsftpd.conf
        echo "chroot_local_user=YES" | sudo tee -a /etc/vsftpd.conf
        echo "allow_writeable_chroot=YES" | sudo tee -a /etc/vsftpd.conf
        echo "pasv_enable=Yes" | sudo tee -a /etc/vsftpd.conf
        echo "pasv_min_port=10000" | sudo tee -a /etc/vsftpd.conf
        echo "pasv_max_port=10100" | sudo tee -a /etc/vsftpd.conf
  
        sudo useradd -m luan
        
        sudo echo "luan:senha" | sudo chpasswd

        sudo mkdir /home/luan/ftp_dir

        sudo local_root=/home/luan/ftp_dir

        sudo chown luan:luan /home/luan/ftp_dir
        
        sudo systemctl restart vsftpd
      SHELL
    end
  
    config.vm.define "mysql_server" do |db|
      db.vm.box = "ubuntu/bionic64"
      db.vm.network "private_network", ip: "192.168.56.102"
      db.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y mysql-server
  
        sudo mysql -e "CREATE USER 'vagrant'@'localhost' IDENTIFIED BY 'vagrant';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'vagrant'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"
  
        sudo mysql -e "CREATE DATABASE empresa;"
        sudo mysql -e "USE empresa; CREATE TABLE funcionarios (id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255), cargo VARCHAR(255));"
      SHELL
    end
  
  end
  