version: '3.9'

services:
  mongo:
    image: mongo
    container_name: 'db'
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  backend:
    image: luancoelhobr/irs-backend:latest
    container_name: 'backend'
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      MONGO_URI: "mongodb://mongo:27017/communicationapp"

  frontend:
    image: luancoelhobr/irs-frontend:latest
    container_name: 'frontend'
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=18.229.164.142
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
