# Use a imagem base do Nginx
FROM nginx:latest

# Copie o arquivo de configuração default.conf para a pasta de configuração do Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

# Copie os arquivos estáticos da aplicação (index.html) para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html
