version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - database

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: unitins
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XidErsEntLET